#ifndef SIREFLECT_TEST_IMPL_H
#define SIREFLECT_TEST_IMPL_H

void sireflect_test_impl_builtin_types(void);
void sireflect_test_impl_native_types(void);
void sireflect_test_impl_kind_helpers(void);
void sireflect_test_impl_type_is_struct_helper(void);
void sireflect_test_impl_type_is_struct_asserts(void);

void sireflect_test_impl_empty_struct(void);
void sireflect_test_impl_primitive_fields(void);
void sireflect_test_impl_mixed_alignment(void);
void sireflect_test_impl_field_copy(void);

void sireflect_test_impl_pointer_field(void);
void sireflect_test_impl_pointer_compat_field(void);
void sireflect_test_impl_raw_pointer_field(void);

void sireflect_test_impl_array_field(void);
void sireflect_test_impl_struct_array_field(void);
void sireflect_test_impl_repeated_array_type(void);
void sireflect_test_impl_pointer_array_field(void);
void sireflect_test_impl_matrix_array_field(void);
void sireflect_test_impl_pointer_matrix_field(void);

void sireflect_test_impl_multiple_primitive_declarators(void);
void sireflect_test_impl_multiple_struct_declarators(void);
void sireflect_test_impl_multiple_array_declarators(void);
void sireflect_test_impl_multiple_pointer_declarators(void);
void sireflect_test_impl_multiple_mixed_declarators(void);

void sireflect_test_impl_qualified_scalar_fields(void);
void sireflect_test_impl_qualified_pointer_field(void);
void sireflect_test_impl_qualified_multiple_declarators(void);

void sireflect_test_impl_multi_token_builtin_registry(void);
void sireflect_test_impl_multi_token_fields(void);
void sireflect_test_impl_multi_token_arrays_and_pointers(void);

void sireflect_test_impl_try_register_valid_struct(void);
void sireflect_test_impl_try_register_invalid_descriptor(void);
void sireflect_test_impl_try_register_unknown_type_returns_invalid(void);
void sireflect_test_impl_try_register_array_errors_return_invalid(void);
void sireflect_test_impl_try_register_declarator_errors_return_invalid(void);
void sireflect_test_impl_try_register_existing_incompatible_type_returns_invalid(void);
void sireflect_test_impl_try_register_registry_usable_after_failure(void);
void sireflect_test_impl_try_register_error_message_persists(void);
void sireflect_test_impl_try_register_error_cleared_by_public_call(void);
void sireflect_test_impl_try_register_error_cleared_by_registry_fini(void);

void sireflect_test_impl_unknown_type_asserts(void);
void sireflect_test_impl_empty_array_asserts(void);
void sireflect_test_impl_zero_array_asserts(void);
void sireflect_test_impl_alpha_array_count_asserts(void);
void sireflect_test_impl_missing_array_end_asserts(void);
void sireflect_test_impl_nested_empty_array_asserts(void);
void sireflect_test_impl_missing_declarator_asserts(void);
void sireflect_test_impl_post_pointer_qualifier_asserts(void);
void sireflect_test_impl_unsupported_type_specifier_asserts(void);
void sireflect_test_impl_unknown_type_diagnostic(void);
void sireflect_test_impl_empty_array_diagnostic(void);
void sireflect_test_impl_zero_array_diagnostic(void);
void sireflect_test_impl_alpha_array_count_diagnostic(void);
void sireflect_test_impl_missing_array_end_diagnostic(void);
void sireflect_test_impl_nested_empty_array_diagnostic(void);
void sireflect_test_impl_missing_declarator_diagnostic(void);
void sireflect_test_impl_post_pointer_qualifier_diagnostic(void);
void sireflect_test_impl_unsupported_type_specifier_diagnostic(void);

#endif
