// Comment out this line when using as DLL
#define sireflect_STATIC
#ifndef SIREFLECT_H
#define SIREFLECT_H

/* This generated file contains includes for project dependencies */
/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef SIREFLECT_BAKE_CONFIG_H
#define SIREFLECT_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Convenience macro for exporting symbols */
#ifndef sireflect_STATIC
#if defined(sireflect_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define SIREFLECT_API __declspec(dllexport)
#elif defined(sireflect_EXPORTS)
  #define SIREFLECT_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define SIREFLECT_API __declspec(dllimport)
#else
  #define SIREFLECT_API
#endif
#else
  #define SIREFLECT_API
#endif

#endif

#endif

